[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.build]
cmds = [
    "mkdir -p dist",
    "cp -r src/* dist/",
    "npm install"
]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "3000"